<?php

$lang['army1_desc'] = 'Hoplites are heavily armored spearmen from the towns` middle classes. They form the heart of every Greek army. In the so-called `Phalanx` formation they push forward in an unstoppable wall of spears and shields.';
$lang['army2_desc'] = 'This powerful machine moves like a person on the battlefield, but has a superhuman hit strength. Stones, arrows and swords simply bounce off it. Woe betide anyone who dares to oppose it!';
$lang['army3_desc'] = 'Spearmen are conscripts from the rural population, that go into battle with light armor and basic spears. They do not usually have a chance against professional soldiers.';
$lang['army4_desc'] = 'Sword fighters are usually barely armored and fight without shields to retain their mobility. Thus they can circulate around the immobile Phalanx formation and attack from the flanks.';
$lang['army5_desc'] = 'Slings are light and cheap weapons. Nevertheless, they are difficult to handle. On the battlefield they barely cause any damage to armoured opponents, but at least their munition is readily available.';
$lang['army6_desc'] = 'Bows are a very popular hunting equipment, so it is very easy to recruit archers amongst citizens. Military training turns simple citizens into formidable long-range combat troops.';
$lang['army7_desc'] = 'Shots from the sulfur carbine can penetrate even the most durable armour. However, due to its sight line, only a single row of archers can fire, while the rest has to reload.';
$lang['army8_desc'] = 'Powerful men swing the massive tree trunk against the enemy gates, until they give way and the men run for cover under the roof. It might only be useful for gates and walls, but at least it does not need any munition.';
$lang['army9_desc'] = 'Catapults sling huge rocks against opponents` defence facilities and thus they can destroy even the strongest stone walls. However they are less useful for defense against enemy armed forces.';
$lang['army10_desc'] = 'The mortar fires explosive shells against the walls of a besieged city. No building can withstand this destructiveness. However, the rare munition for it has to be brought along additionally, so shots fired need to be very well-targeted.';
$lang['army11_desc'] = 'A novel flying machine that is fast, versatile and not dependant on the direction of the wind - we can hunt cowardly enemies that want to attack us from the skies with it!';
$lang['army12_desc'] = 'Our inventors have discovered that the sun is so hot because it attracts warm air. That is why a balloon filled with hot air also rises in direction of the sun and our soldiers can throw explosive shells down on our enemies from up there.';
$lang['army13_desc'] = 'Your army`s cooks know exactly how to give new courage to the warriors and heroes in the encampment: A glass of wine and a stew, just like mum used to make! If they take the evening to remember what they are fighting for, enemies will find it very hard to wear them down.';
$lang['army14_desc'] = 'These doctors have voluntarily enlisted to help tend to the wounds of those on the battle front. They can remove arrow heads, bandage up sword wounds and have enough ice available for soldiers` heads should enemies attack with slingshots.';
$lang['army15_desc'] = 'The main barbarian battle troops are terrifying warriors who throw themselves into battle with a wild roar and ensuing chaos. However, they barely have a chance against the disciplined Greek Phalanxes with their primitive armor.';
$lang['army16_desc'] = 'Equipped with a simple ram at the stable bow, this ship is the primary battle ship of the marines. A dozen strong rowers power it in order to ram the spur against the opposing hull. That alone is often enough to make an enemy ship sink.';
$lang['army17_desc'] = 'At the fire ship`s bow there is flame thrower, which sprays Greek fire over the sea. Even on the ocean`s surface, the mixture keeps on burning and creates a bed of flames. A terrifying close combat ship';
$lang['army18_desc'] = 'An invention that would have even astonished Heron: The paddle-wheel-ram uses the movement impulse of a massive aeolipile as well as paddle wheels to drive into opposing ships with an enormous amount of power and speed. The ship does not need a big crew either.';
$lang['army19_desc'] = 'This ship contains a ballista, which was originally meant for firing grappling hooks. However, the ballista is also very valuable as a precise long-range combat weapon, as it hits the enemy under the waterline, even though it does not cause a large amount of damage.';
$lang['army20_desc'] = 'The catapult at the deck of the ship is smaller than its counterpart on land due to a lack of space. The ocean waves make it very imprecise, but it does fire clay jugs of burning oil, which leave dangerous little oil slicks behind at sea.';
$lang['army21_desc'] = 'The mortar ship has an especially large hull with a high water displacement, so that it can withstand the enormous recoil of the mortar. If the fuse of a missile is correctly measured, the powerful projectile explodes just over the enemy deck.';
$lang['army22_desc'] = 'A boat that sails below the water`s surface is the ultimate sea weapon. Battleships also cannot defend themselves against them. Enemies will merely have their own diving boats at hand as a countermeasure.';
$lang['army23_desc'] = 'Trade ships are the most important support for your island empire. No matter whether they have to transport goods, units or news: your seamen will make sure, that everything arrives at its destination quick and safely.';

